package com.investigatorsapp.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storeDaoConfig;
    private final DaoConfig traceDaoConfig;

    private final StoreDao storeDao;
    private final TraceDao traceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        traceDaoConfig = daoConfigMap.get(TraceDao.class).clone();
        traceDaoConfig.initIdentityScope(type);

        storeDao = new StoreDao(storeDaoConfig, this);
        traceDao = new TraceDao(traceDaoConfig, this);

        registerDao(Store.class, storeDao);
        registerDao(Trace.class, traceDao);
    }
    
    public void clear() {
        storeDaoConfig.getIdentityScope().clear();
        traceDaoConfig.getIdentityScope().clear();
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

    public TraceDao getTraceDao() {
        return traceDao;
    }

}
