package com.investigatorsapp.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STORE.
 */
public class Store {

    /** Not-null value. */
    private String salerno;
    private String userid;
    private String jobid;
    private String token;
    private String polygonid;
    private String polygonname;
    private String time;
    private String status;
    private String custname;
    private String custperson;
    private String fphone;
    private String telephone;
    private String email;
    private String fax;
    private String country;
    private String province;
    private String city;
    private String district;
    private String address;
    private String zipcode;
    private String custtype;
    private String producttype;
    private String channeltype;
    private String stationnum;
    private String workernum;
    private String lat1;
    private String lng1;
    private String lat2;
    private String lng2;
    private String photoname;
    private String isshell;
    private String iscastrol;
    private String ismobil;
    private String monthoil;
    private String audioname;

    public Store() {
    }

    public Store(String salerno) {
        this.salerno = salerno;
    }

    public Store(String salerno, String userid, String jobid, String token, String polygonid, String polygonname, String time, String status, String custname, String custperson, String fphone, String telephone, String email, String fax, String country, String province, String city, String district, String address, String zipcode, String custtype, String producttype, String channeltype, String stationnum, String workernum, String lat1, String lng1, String lat2, String lng2, String photoname, String isshell, String iscastrol, String ismobil, String monthoil, String audioname) {
        this.salerno = salerno;
        this.userid = userid;
        this.jobid = jobid;
        this.token = token;
        this.polygonid = polygonid;
        this.polygonname = polygonname;
        this.time = time;
        this.status = status;
        this.custname = custname;
        this.custperson = custperson;
        this.fphone = fphone;
        this.telephone = telephone;
        this.email = email;
        this.fax = fax;
        this.country = country;
        this.province = province;
        this.city = city;
        this.district = district;
        this.address = address;
        this.zipcode = zipcode;
        this.custtype = custtype;
        this.producttype = producttype;
        this.channeltype = channeltype;
        this.stationnum = stationnum;
        this.workernum = workernum;
        this.lat1 = lat1;
        this.lng1 = lng1;
        this.lat2 = lat2;
        this.lng2 = lng2;
        this.photoname = photoname;
        this.isshell = isshell;
        this.iscastrol = iscastrol;
        this.ismobil = ismobil;
        this.monthoil = monthoil;
        this.audioname = audioname;
    }

    /** Not-null value. */
    public String getSalerno() {
        return salerno;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSalerno(String salerno) {
        this.salerno = salerno;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getJobid() {
        return jobid;
    }

    public void setJobid(String jobid) {
        this.jobid = jobid;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getPolygonid() {
        return polygonid;
    }

    public void setPolygonid(String polygonid) {
        this.polygonid = polygonid;
    }

    public String getPolygonname() {
        return polygonname;
    }

    public void setPolygonname(String polygonname) {
        this.polygonname = polygonname;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCustname() {
        return custname;
    }

    public void setCustname(String custname) {
        this.custname = custname;
    }

    public String getCustperson() {
        return custperson;
    }

    public void setCustperson(String custperson) {
        this.custperson = custperson;
    }

    public String getFphone() {
        return fphone;
    }

    public void setFphone(String fphone) {
        this.fphone = fphone;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getCusttype() {
        return custtype;
    }

    public void setCusttype(String custtype) {
        this.custtype = custtype;
    }

    public String getProducttype() {
        return producttype;
    }

    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }

    public String getChanneltype() {
        return channeltype;
    }

    public void setChanneltype(String channeltype) {
        this.channeltype = channeltype;
    }

    public String getStationnum() {
        return stationnum;
    }

    public void setStationnum(String stationnum) {
        this.stationnum = stationnum;
    }

    public String getWorkernum() {
        return workernum;
    }

    public void setWorkernum(String workernum) {
        this.workernum = workernum;
    }

    public String getLat1() {
        return lat1;
    }

    public void setLat1(String lat1) {
        this.lat1 = lat1;
    }

    public String getLng1() {
        return lng1;
    }

    public void setLng1(String lng1) {
        this.lng1 = lng1;
    }

    public String getLat2() {
        return lat2;
    }

    public void setLat2(String lat2) {
        this.lat2 = lat2;
    }

    public String getLng2() {
        return lng2;
    }

    public void setLng2(String lng2) {
        this.lng2 = lng2;
    }

    public String getPhotoname() {
        return photoname;
    }

    public void setPhotoname(String photoname) {
        this.photoname = photoname;
    }

    public String getIsshell() {
        return isshell;
    }

    public void setIsshell(String isshell) {
        this.isshell = isshell;
    }

    public String getIscastrol() {
        return iscastrol;
    }

    public void setIscastrol(String iscastrol) {
        this.iscastrol = iscastrol;
    }

    public String getIsmobil() {
        return ismobil;
    }

    public void setIsmobil(String ismobil) {
        this.ismobil = ismobil;
    }

    public String getMonthoil() {
        return monthoil;
    }

    public void setMonthoil(String monthoil) {
        this.monthoil = monthoil;
    }

    public String getAudioname() {
        return audioname;
    }

    public void setAudioname(String audioname) {
        this.audioname = audioname;
    }

}
